# <option value="aframer">african and african american studies</option>

classes = [["arts", "arts"], ["aframer", "african/-american studies"], ["afrikaan", "afrikaans"],
["akkad", "akkadian"],
["amstdies", "american studies"],
["amharic", "amharic"],
["ane", "ancient near east"],
["anthro", "anthropology"],
["apcomp", "applied computation"],
["apmth", "applied math"],
["apphy", "applied physics"],
["arabic", "arabic"],
["armen", "armenian"],
["afvs", "arts, film, and visual studies"],
["astron", "astronomy"],
["bcmp", "bio chem and molecular pharm"],
["bbs", "bio/-medical sci"],
["bph", "bio sci in public health"],
["be", "biomedical engineering"],
["bmif", "biomedical informatics"],
["biophys", "biophysics"],
["biostat", "biostatistics"],
["bcs", "bosnian, croatian and serbian"],
["catalan", "catalan"],
["cellbio", "cell biology"],
["celtic", "celtic"],
["cpb", "chemical and physical biology"],
["chem", "chemistry"],
["chnshist", "chinese history"],
["chnslit", "chinese literature"],
["clasarch", "classical archaeology"],
["clasheb", "classical hebrew"],
["clasphil", "classical philology"],
["clsstdy", "classical studies"],
["classic", "classics"],
["complit", "comparative literature"],
["compsci", "computer science"],
["czech", "czech"],
["design", "design"],
["drb", "developmental and regenerative biology"],
["eafm", "east asian film and media studies"],
["epsci", "earth and planetary sciences"],
["eabs", "east asian buddhist studies"],
["eas", "east asian studies"],
["ec", "economics"],
["egyptarb", "egyptian arabic"],
["egyptian", "egyptian"],
["engsci", "engineering sciences"],
["english", "english"],
["ese", "environ sci and engineering"],
["espp", "environ sci and public policy"],
["emr", "ethnicity, migration and rights"],
["expos", "expository writing"],
["folkmyth", "folklore and mythology"],
["french", "french"],
["frsemr", "freshman seminar"],
["gened", "general education"],
["genetic", "genetics"],
["german", "german"],
["ghhp", "global health and health policy"],
["gov", "government"],
["gsas", "graduate school of arts and sciences"],
["greek", "greek"],
["gullah", "gullah"],
["haitian", "haitian"],
["hausa", "hausa"],
["health policy", "health policy"],
["hebrew", "hebrew"],
["hindurd", "hindi-urdu"],
["hist", "history"],
["histlit", "history and literature"],
["haa", "history of art and architecture"],
["histsci", "history of science"],
["hbtm", "human bio and translational med"],
["heb", "human evolutionary bio"],
["hum", "humanities"],
["igbo", "igbo"],
["immun", "immunology"],
["irish", "irish"],
["islamciv", "islamic civilizations"],
["ital", "italian"],
["japan", "japanese"],
["japnhist", "japanese history"],
["jewishst", "jewish studies"],
["korean", "korean"],
["korhist", "korean history"],
["latin", "latin"],
["lps", "life and physical sciences"],
["ls", "life science"],
["ling", "linguistics"],
["math", "mathematics"],
["medsci", "medical sciences"],
["medvlstd", "medieval studies"],
["microbi", "microbiology"],
["mbb", "mind, brain and behavior"],
["modgrk", "modern greek"],
["modheb", "modern hebrew"],
["modmdest", "modern middle east"],
["mcb", "molecular and cellular biology"],
["music", "music"],
["nec", "near eastern civilizations"],
["nep", "nepali"],
["neurobio", "neurobiology"],
["neuro", "neuro"],
["oeb", "organismic and evolutionary bio"],
["persian", "persian"],
["phil", "philosophy"],
["ps", "physical sciences"],
["phys", "physics"],
["polish", "polish"],
["portug", "portuguese"],
["psy", "psychology"],
["rsea", "regional studies — east asia"],
["religion", "religion"],
["romlang", "romance languages"],
["romstd", "romance studies"],
["rsra", "russia, e. europe and central asia"],
["russ", "russian"],
["sanskirt", "sanskirt"],
["scand", "scandinavian"],
["shona", "shona"],
["slavic", "slavic"],
["socstd", "social studies"],
["sociol", "sociology"],
["sas", "south asian studies"],
["spanish", "spanish"],
["shbt", "speech and hearing sciences"],
["stat", "statistics"],
["scrb", "stem cell and regenerative bio"],
["sudanese", "sudanese"],
["sumerian", "sumerian"],
["swahili", "swahili"],
["swedish", "swedish"],
["syriac", "syriac"],
["sysbio", "systems biology"],
["tam", "tamil"],
["thi", "thai"],
["tdm", "theater, dance and media"],
["tibet", "tibetan"],
["tigrinya", "tigrinya"],
["turkish", "turkish"],
["twi", "twi"],
["ukra", "ukranian"],
["uyghur", "uyghur"],
["vietnam", "vietnamese"],
["virology", "virology"],
["welsh", "welsh"],
["wstafrcn", "west african pidgin"],
["wgs", "woman, gender and sexuality"],
["yiddish", "yiddish"],
["yoruba", "yoruba"],
["zulu", "zulu"]]

for i in range(len(classes)):
    first = classes[i][0]
    last = classes[i][1]
    print(f'<option value="{first}">{last}</option>')